Novo cabeçalho mais informativo
manualdousuario/dez pull request #44
Opened 2024-02-23 21:32 UTC by rghedin

* Altera logo e cabeçalho
* Diminui margens entre elementos (leiaute mais denso)
* Remove itens agora redundantes do rodapé
* Altera cor do link “Continue lendo” (``)

Resolve #43

2024-02-25 13:27 UTC, claromes requested changes

2024-02-25 13:27 UTC, claromes commented on style.css
> +		width: 100%;
Esse `width` deixa o form quebrado em telas menores de 620px em browsers baseados no Chromium (Brave, Chrome, por exemplo). No Firefox está ok; Excluindo resolve o problema. Não sei como fica no Safari.

![Captura de tela 2024-02-25 102058](https://github.com/manualdousuario/dez/assets/28742647/f524b2c6-709b-4e31-8aaf-96fe575e31f3)

2024-02-25 15:48 UTC, rghedin commented on style.css
> +		width: 100%;
No Safari precisa dele para o form ocupar toda a largura da tela 😄

Vou removê-lo — melhor não quebrar em lugar algum e o Safari exibir o form um pouco mais curto.

2024-02-25 17:50 UTC, claromes commented
Achei outra inconsistência: o texto no footer "Associado à..." não fica alinhado ao centro em telas maiores por conta do `max-width: var(--line-length);` que a tag p está recebendo na linha 162. Pra resolver basta colocar `max-width: none;` na class `site-footer-footer`.

2024-02-25 20:39 UTC, rghedin commented
Boa sacada, @claromes! Corrigido.

2024-02-26 07:10 UTC, claromes approved these changes

2024-02-26 07:10 UTC, merged