Destaca ícone do menu do usuário
manualdousuario/dez pull request #63
Opened 2024-05-26 21:46 UTC by rghedin

* Adiciona cor de fundo ao ícone do menu do usuário
* Muda a posição do ícone do menu do usuário para o final do menu
* Adiciona borda para melhorar contraste do menu do usuário aberto

2024-05-26 21:46 UTC, rghedin commented
Se estiver tudo certo, pode gerar o release, @claromes, por favor.

2024-06-05 15:55 UTC, claromes requested changes
Além da linha 1478, na linha 1236 mudar `max-width` para 710px.

O menu aberto não está alinhado e o max-width precisa ser maior:
![Captura de tela 2024-06-05 124555](https://github.com/manualdousuario/dez/assets/28742647/8f570ae6-01eb-40ee-afed-c46c12038008)

![Captura de tela 2024-06-05 124704](https://github.com/manualdousuario/dez/assets/28742647/9908bee4-594d-498e-8f09-d11017549655)

2024-06-05 15:55 UTC, claromes commented on style.css
>  	right: -100%;
Alterar para 0%

2024-06-05 17:50 UTC, claromes approved these changes

2024-06-05 17:50 UTC, merged

2024-06-05 17:51 UTC, claromes commented
@rghedin Pode fazer o release, o espero o #60?

2024-06-05 18:00 UTC, rghedin commented
Pode fazer, @claromes