Novos blocos `.ctx` e outros ajustes
manualdousuario/dez pull request #65
Opened 2024-06-15 13:33 UTC by rghedin

* Altera leiaute dos blocos `ctx-`, prevê uso de `label` para sinalizar o tipo de bloco (ajuda na acessibilidade) e nova classe genérica `ctx` (mantém as classes antigas para retrocompatibilidade).
* Acrescenta bordas ao menu principal (`ul.nav-menu`) e botão do menu do leitor (`.menu-toggle-icon`)
* Inverte posições dos links de responder e curtir comentários
* Bloqueia o carregamento do arquivo `jlad-frontend.css`, do plugin Just Likes and Dislikes, no front-end (via `functions.php`)
* Ajustes no `style.css` para o plugin Just Likes and Dislikes

2024-06-20 05:46 UTC, claromes requested changes
- Na linha 1351, na media query, mudar para 432px (mesmo comentário do calc()).

  Uma sugestão para essa mesma `@media`:
  Acrescentar um `gap` maior entre os ícones
  ```css
  .main-navigation {
      gap: 1.5rem;
  }
  ```

- Ajustar ícone do Just Likes and Dislikes no modo claro

2024-06-20 05:46 UTC, claromes commented on header.php
> +				$icon_nav .= '<a href="/feed/"><img src="/wp-content/themes/dez/img/icone-rss-outline.svg" alt="Feed RSS" width="26" height="26" /></a>';
Podemos seguir o padrão dos outros ícones e usar o SVG no CSS?

2024-06-20 05:46 UTC, claromes commented on style.css
>  @media (max-width: 710px) {
Alterar para 715px (o ideal mesmo é a gente usar um calc(), caso contrário qualquer mudança no header vamos ter que ajustar esse número)

2024-06-20 10:26 UTC, rghedin commented on style.css
>  @media (max-width: 710px) {
Fiz as alterações sugeridos para as media queries, mas não manjo usar `calc()` nesse contexto. Como seria isso?

2024-06-20 10:58 UTC, rghedin commented on style.css
>  @media (max-width: 710px) {
Saquei.

Considerando que alterações no header são raras (assim esperamos 🙏), talvez seja viável continuarmos levando assim, no modo manual/sem `calc()`?

2024-06-20 11:14 UTC, claromes commented on style.css
>  @media (max-width: 710px) {
Ah, sim! Só comentei.

2024-06-21 15:29 UTC, claromes requested changes
O ícone nos comentários, no modo claro, continua branco.
Vi que você fez alterações no formulário, mas o gap continuou. Pensei que alinhado seria mais adequado, não? Está assim agora:

![Captura de tela 2024-06-21 122704](https://github.com/manualdousuario/dez/assets/28742647/5a7882d5-56a1-40e3-80e0-0f05a2e68839)

Se não quiser alterar, pode ignorar isso.

2024-06-22 00:26 UTC, claromes commented
Então, bora!

2024-06-22 00:27 UTC, claromes approved these changes

2024-06-22 00:27 UTC, merged