Pequenos ajustes gerais
manualdousuario/dez pull request #70
Opened 2024-07-22 11:31 UTC by rghedin

* Corrige cor de fundo do `label` da classe `.ctx-parceiros`.
* Padroniza formatação dos de links de navegação (`.posts-navigation a`).
* Altera cabeçalho da página de resultados da pesquisa (`.search-results .page-header`).
* Encolhe um pouco o formulário de pesquisa no cabeçalho em telas grandes.
* Altera ordem das inserções de shortcodes (`sc`) no `index.php`.

2024-07-27 12:37 UTC, rghedin commented
Coloquei o link para mesas de trabalho no menu depois de notar, nos relatórios da Algolia (novo motor de pesquisas do site), que “mesas de trabalho” e afins são os termos mais pesquisados no site. Havia espaço e acho que vai facilitar para o pessoal, né?

2024-07-28 00:46 UTC, claromes requested changes
Na linha 1276 o `max-width` precisa ser ajustado. Coloca `calc(100vh - 220px)`, assim já definimos automaticamente. 220 é da imagem.

Eu talvez colocaria o item Mesas, depois do Órbita.

2024-07-28 00:46 UTC, claromes commented on style.css
> +	font-size: var(--fs-2);
Sugestão: `--fs-1` segue mais o estilo da página.

2024-07-28 13:08 UTC, rghedin commented
Feito!

Explica para mim como você recalcula o `max-width` da media querie, por favor?

2024-07-31 03:15 UTC, claromes commented
@rghedin Neste caso aqui não foi feito o cálculo que deveria ser feito. Só usei o 220px como referência do logo e usei vh (viewport height) para calcular o total da tela. Foi arbitrário mesmo. No cálculo correto, deve se considerar o header todo, porém calculando automaticamente os menus (que são os que mudam).

2024-07-31 03:16 UTC, claromes approved these changes

2024-07-31 03:16 UTC, merged