v2
manualdousuario/dez pull request #8
Opened 2023-10-27 19:50 UTC by rghedin

* Refatoração completa do CSS: estrutura reorganizada, mais uso de flexboxes e (bem) menos uso de media queries;
* Acrescentado dimensões e alt text à imagem do menu hambúrguer;
* littlefoot.js atualizado para 4.0.1.

2023-10-30 13:07 UTC, claromes requested changes
Eu aprovei mas depois vi um erro no css, quando a tela está menor. Fiz uma sugestão.

2023-10-30 13:23 UTC, rghedin commented on style.css
> +		margin: 0 0 2rem;
Boa, Clarissa! Acho que já corrigi esses detalhes nas mudanças que fiz localmente desde que subi a v2 em produção. Vou submeter um novo PR com todas as alterações em instantes.

2023-10-31 09:15 UTC, claromes commented on style.css
> +	display: flex;
```suggestion
	display: inline-flex;
```

2023-10-31 10:10 UTC, claromes requested changes
Além das duas alterações, só um comentário: o css do Órbita está no plugin e no tema. Não seria melhor deixar somente em um lugar? Eu acho que seria bom deixar somente no tema, assim qualquer mudança aqui altera lá tbm.

2023-10-31 10:31 UTC, rghedin commented on style.css
> +		margin: 0 0 2rem;
Hmmm, vou acrescentar a correção proposta.

2023-10-31 10:33 UTC, rghedin commented
> Além das duas alterações, só um comentário: o css do Órbita está no plugin e no tema. Não seria melhor deixar somente em um lugar? Eu acho que seria bom deixar somente no tema, assim qualquer mudança aqui altera lá tbm.

Sim, é o ideal manter só no Órbita. Coloquei no do dez para não ficar quebrado enquanto não sai uma atualização do Órbita. Vou agrupar essas gambiarras e sinalizá-las com um comentário para removermos quando o Órbita for atualizado.

2023-11-04 17:55 UTC, claromes approved these changes

2023-11-04 18:22 UTC, merged